name: Consul Cluster
description: |
  Consul Cluster Installation (without certs)
version: 0.8-rancher1
category: Clustering
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'
