version: '2'
.catalog:
  name: GlusterFS
  version: v1.0
  description: Clustered deployment of GlusterFS
  questions:
    - variable: network_mode
      label: "Network Mode"
      type: "string"
      default: "container:glusterfs-server"
      required: true
services:
  glusterfs-server:
    scale: 3
    retain_ip: true
    metadata:
      volume_name: "my_vol"
