catalog:
  name: GlusterFS
  version: v1.0
  description: Clustered deployment of GlusterFS
  questions:
    - variable: volume_name
      label: "Volume Name"
      type: "string"
      required: true
      default: "my_vol"
    - variable: network_mode
      label: "Network Mode"
      type: "string"
      default: "container:glusterfs-server"
      required: true
glusterfs-server:
  scale: 3
  retain_ip: true
  metadata:
    volume_name: "${volume_name}"
